name: RankShopUI
main: RankShop\Main
api: [3.0.0-ALPHA12, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.40, 3.50]
version: 0.1
author: Zenter.  

commands:
 rankshop:
  description: "BUY RANKS LIKE VIP AND MORE. CHEAP PRICE"
